# Allow for locked-in custom names derived from colors and word list

configuration_file_version: 1

wordlist_file: words.txt
activation_length: 10
cost:
  ==: org.bukkit.inventory.ItemStack
  type: EXP_BOTTLE
  amount: 10
color:
  chars: [1, 10]
  function: com.programmerdan.minecraft.wordbank.functions.Modulus
  function_terms:
  - 15
word:
  max: 3
  count:
    chars: [2, 5]
    function: com.programmerdan.minecraft.wordbank.functions.LinearMap
    function_terms:
    - 1
    - 3 
  1:
    chars: [1, 3, 4, 10]
    function: com.programmerdan.minecraft.wordbank.functions.HashMap
    function_terms:
    - 1
    - 10000
  2:
    chars: [2, 4, 5, 9]
    function: com.programmerdan.minecraft.wordbank.functions.HashMap
    function_terms:
    - 1
    - 10000
  3:
    chars: [3, 6, 7, 8]
    function: com.programmerdan.minecraft.wordbank.functions.HashMap
    function_terms:
    - 1
    - 10000
